CREATE TABLE MOVIE_CLASSIFICATION (
	ID SERIAL PRIMARY KEY,
	DESCRIPTION VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE CHAIR_TYPE (
	ID SERIAL PRIMARY KEY,
	DESCRIPTION VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE ROOM (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	CAPACITY INT NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL
);

CREATE TABLE MOVIE (
	ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	MOVIE_CLASSIFICATION_ID BIGINT NOT NULL,
	DURATION INT NOT NULL,
	FOREIGN KEY (MOVIE_CLASSIFICATION_ID) REFERENCES MOVIE_CLASSIFICATION(ID)
);

CREATE TABLE CHAIR (
	ID SERIAL PRIMARY KEY,
	NUMBER VARCHAR(100),
	OCCUPIED BOOLEAN NOT NULL,
	CHAIR_TYPE_ID BIGINT NOT NULL,
	ROOM_ID BIGINT NOT NULL,
	FOREIGN KEY (CHAIR_TYPE_ID) REFERENCES CHAIR_TYPE(ID),
	FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID)
);


CREATE TABLE SESSION (
	ID SERIAL PRIMARY KEY,
	START_DATE_TIME TIMESTAMP NOT NULL,
	END_DATE_TIME TIMESTAMP NOT NULL,
	ROOM_ID BIGINT NOT NULL,
	MOVIE_ID BIGINT NOT NULL,
	FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID),
	FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID)
);


INSERT INTO MOVIE_CLASSIFICATION (ID, DESCRIPTION)
VALUES
    (1, 'FREE'),
    (2, '10+'),
    (3, '12+'),
    (4, '14+'),
    (5, '16+'),
    (6, '18+');


INSERT INTO CHAIR_TYPE (ID, DESCRIPTION)
VALUES
	(1, 'DEFAULT'),
	(2, 'OBSESITY'),
	(3, 'DISABILITY');
