CREATE TABLE MOVIE_CLASSIFICATION (
	ID SERIAL PRIMARY KEY,
	DESCRIPTION VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE CHAIR_TYPE (
	ID SERIAL PRIMARY KEY,
	DESCRIPTION VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE ROOM (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	CAPACITY INT NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL
);

CREATE TABLE MOVIE (
	ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	MOVIE_CLASSIFICATION_ID BIGINT NOT NULL,
	FOREIGN KEY (MOVIE_CLASSIFICATION_ID) REFERENCES MOVIE_CLASSIFICATION(ID)
);

CREATE TABLE CHAIR (
	ID SERIAL PRIMARY KEY,
	NUMBER VARCHAR(100),
	OCCUPIED BOOLEAN NOT NULL,
	CHAIR_TYPE_ID BIGINT NOT NULL,
	ROOM_ID BIGINT NOT NULL,
	FOREIGN KEY (CHAR_TYPE_ID) REFERENCES CHAIR_TYPE(ID),
	FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID)
);


CREATE TABLE SESSION (
	ID SERIAL PRIMARY KEY,
	START_DATE_TIME TIMESTAMP NOT NULL,
	END_DATE_TIME TIMESTAMP NOT NULL,
	ROOM_ID BIGINT NOT NULL,
	MOVIE_ID BIGINT NOT NULL,
	FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID),
	FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID)
);


INSERT INTO MOVIE_CLASSIFICATION (DESCRIPTION)
VALUES
	('FREE'),
	('TEN YEARS'),
	('TWELVE YEARS'),
	('FOURTEEN YEARS'),
	('SIXTEEN YEARS'),
	('EIGHTEEN YEARS');


INSERT INTO CHAIR_TYPE (DESCRIPTION)
VALUES
	('DEFAULT'),
	('OBSESITY'),
	('DISABILITY');
	


	
	


